# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form3(object):
    def setupUi(self, Form3):
        Form3.setObjectName("Form3")
        Form3.resize(734, 637)
        self.frame = QtWidgets.QFrame(Form3)
        self.frame.setGeometry(QtCore.QRect(150, 80, 451, 481))
        self.frame.setStyleSheet("background-image: url(:/background/UI/background3.jpg);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 110, 61, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background:transparent;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 190, 61, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent;")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(70, 270, 61, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background:transparent;")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(180, 30, 101, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(180, 360, 91, 31))
        self.pushButton.setStyleSheet("background-image: url(:/background/UI/whitebackground.jpg);")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(140, 110, 241, 31))
        self.lineEdit.setStyleSheet("background-image: url(:/background/UI/whitebackground.jpg);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 190, 241, 31))
        self.lineEdit_2.setStyleSheet("background-image: url(:/background/UI/whitebackground.jpg);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 270, 241, 31))
        self.lineEdit_3.setStyleSheet("background-image: url(:/background/UI/whitebackground.jpg);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 0, 31, 28))
        self.pushButton_2.setStyleSheet("background-image: url(:/background/UI/whitebackground.jpg);")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form3)
        self.pushButton_2.clicked.connect(Form3.exit) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form3)

    def retranslateUi(self, Form3):
        _translate = QtCore.QCoreApplication.translate
        Form3.setWindowTitle(_translate("Form3", "Form"))
        self.label.setText(_translate("Form3", "用户名"))
        self.label_2.setText(_translate("Form3", "账  号"))
        self.label_5.setText(_translate("Form3", "密  码"))
        self.label_7.setText(_translate("Form3", "注册账号"))
        self.pushButton.setText(_translate("Form3", "注册"))
        self.pushButton_2.setText(_translate("Form3", "X"))
import pictures_rc
